// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiPttn5C37_c-jo_1VxaIeOqSCkUdKSS4',
    appId: '1:810187577371:android:1d81c161d6ae8c43c540be',
    messagingSenderId: '810187577371',
    projectId: 'krishi-sech',
    storageBucket: 'krishi-sech.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0tde_u5VBB6Mgzm6jKw93pTlr0RopdQ',
    appId: '1:810187577371:ios:097b73a54d47dfe0c540be',
    messagingSenderId: '810187577371',
    projectId: 'krishi-sech',
    storageBucket: 'krishi-sech.firebasestorage.app',
    androidClientId: '810187577371-89mmeh62aiia2kmhcmvu69hgfaruaqkn.apps.googleusercontent.com',
    iosClientId: '810187577371-f5rshgmavbhockn3onqrl3mehf6ifpuo.apps.googleusercontent.com',
    iosBundleId: 'com.krishisech.app',
  );
}
